// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAauYuhXotbA_YGHnWtsI5F_R_D3SercU8',
    appId: '1:320857733319:web:1f21e3906de7a52cf1e6e2',
    messagingSenderId: '320857733319',
    projectId: 'counsellorconnect-4642a',
    authDomain: 'counsellorconnect-4642a.firebaseapp.com',
    storageBucket: 'counsellorconnect-4642a.firebasestorage.app',
    measurementId: 'G-C19R9218Z4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC41y9e4oZ0OmZ7juh6ZrQ9x_eMZd7EsuU',
    appId: '1:320857733319:android:1323c7b5adf6cd85f1e6e2',
    messagingSenderId: '320857733319',
    projectId: 'counsellorconnect-4642a',
    storageBucket: 'counsellorconnect-4642a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3Gm54crWsAURzOAzczFFyg7nquUnuYpA',
    appId: '1:320857733319:ios:575fd54db148be14f1e6e2',
    messagingSenderId: '320857733319',
    projectId: 'counsellorconnect-4642a',
    storageBucket: 'counsellorconnect-4642a.firebasestorage.app',
    iosBundleId: 'com.example.counsellorconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3Gm54crWsAURzOAzczFFyg7nquUnuYpA',
    appId: '1:320857733319:ios:575fd54db148be14f1e6e2',
    messagingSenderId: '320857733319',
    projectId: 'counsellorconnect-4642a',
    storageBucket: 'counsellorconnect-4642a.firebasestorage.app',
    iosBundleId: 'com.example.counsellorconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAauYuhXotbA_YGHnWtsI5F_R_D3SercU8',
    appId: '1:320857733319:web:7d9126999d612439f1e6e2',
    messagingSenderId: '320857733319',
    projectId: 'counsellorconnect-4642a',
    authDomain: 'counsellorconnect-4642a.firebaseapp.com',
    storageBucket: 'counsellorconnect-4642a.firebasestorage.app',
    measurementId: 'G-BB5PC6FY7P',
  );
}
